name: textly
description: Textly analyzes your text and creates beautiful graphs. Textly does not collect usage data and is completely open source.

publish_to: "none"

version: 2.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.1.14
  flex_color_scheme: ^7.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  msix: ^3.16.2

msix_config:
  display_name: Textly
  publisher_display_name: Tom Vogel
  identity_name: com.tom.textly
  msix_version: 1.0.0.0
  logo_path: C:\Users\vogel\Programmieren\Flutter\Projects\textly\assets\App\appstore.png

flutter:
  uses-material-design: true

  assets:
    - assets/img/